<?php

/**
 * Implements hook_civicrm_buildForm()
 */
function creativecommons_civicrm_buildForm($formName, &$form) {
  if ($formName == 'CRM_Contribute_Form_Contribution_Main') {
    // Set Contributor Source field from url parameters
    if (isset($form->_fields['custom_42'])) {
      $params = drupal_get_query_parameters();
      if (isset($params['utm_campaign'])) {
        $contributor_source = $params['utm_campaign'];
        if (isset($params['utm_source'])) {
          $contributor_source .= '_' . $params['utm_source'];
        }
        $defaults['custom_42'] = $contributor_source;
      }
    }
    // Set Supporter List Opt-in field to checked by default
    $defaults['custom_12'] = '1';
    $form->setDefaults( $defaults );

    if ($form->_submitValues['selectProduct'] == 'no_thanks' && $form->_submitValues['payment_processor'] == 1) {
      unset($form->_submitValues['first_name']);
      unset($form->_submitValues['last_name']);
      unset($form->_submitValues['street_address-6']);
      unset($form->_submitValues['city-6']);
      unset($form->_submitValues['country-6']);
      unset($form->_submitValues['state_province-6']);
      unset($form->_submitValues['postal_code-6']);
    }
  }
}

function creativecommons_civicrm_validateForm($formName, &$fields, &$files, &$form, &$errors) {
  if ($formName == 'CRM_Contribute_Form_Contribution_Main') {
    if ($fields['selectProduct'] != 'no_thanks') {
      $shipping_fields = array(
	'first_name' => 'First Name',
	'last_name' => 'Last Name',
	'street_address-6' => 'Street Address',
	'city-6' => 'City',
	'country-6' => 'Country',
	'state_province-6' => 'State',
	'postal_code-6' => 'Postal Code'
      );
      foreach ($shipping_fields as $key=>$value) {
	if (empty($fields[$key])) {
	  $form->setElementError($key, $value . ' is a required field.');
	}
      }
    }
  }
  return;
}

